### ISSUE TITLE
Internal error when submitting the Custom job operation

### ISSUE THREAD

**Issue by rafaelsf80** [GoogleCloudPlatform/t5x-on-vertex-ai#2]
Hi,
I run **Task 1** from the `getting-started.ipynb` notebook and the Custom job operation fails with internal error after 20-25 minutes.
Logs show no extra verbosity rather than an `Internal error occuered for the current attempt` message.

It can be actually related to the Docker image, since I used an old t5x image from some weeks ago, and worked.

Any help would be appreciated.

```
2022-09-21 14:41:46.017 CEST

service
Waiting for job to be provisioned.

2022-09-21 14:49:30.033 CEST

service
Internal error occurred for the current attempt.
2022-09-21 14:49:30.262 CEST

service
Job failed.
2022-09-21 14:49:30.279 CEST

service
Waiting for job to be provisioned.
2022-09-21 14:57:05.240 CEST

service
Internal error occurred for the current attempt.
2022-09-21 14:57:05.782 CEST

service
Job failed.
2022-09-21 14:57:05.894 CEST

service
Waiting for job to be provisioned.
2022-09-21 15:04:47.024 CEST

service
Internal error occurred for the current attempt.
2022-09-21 15:04:47.540 CEST

service
Job failed.
2022-09-21 15:04:47.546 CEST

service
Job will not be retried, max error retry attempts reached.
```

**Comment by leiterenato** [comment]
Hi @rafaelsf80.
I just built the docker image from scratch and ran the Task 1 in a clean project.
Everything worked OK.

Did you built the dataset successfully? (following the README file)
`tfds build --data_dir $TFDS_DATA_DIR --experimental_latest_version wmt_t2t_translate`

**Comment by rafaelsf80** [comment]
Thanks, it solved the issue.
I skipped that command since, in previous tests, I noticed the custom job itself also downloaded the `wmt_t2t_translate` as part of the training (I saw the files in GCS). So, not sure what's the difference between what `tfds build` does and what the Custom Job does in terms of dataset downloading. 

Also, I do not understand either why it worked with an older image without changing the GCS bucket and without running `tfds build`.  Any clarification would be appreciated.

Would it be possible to skip that command and let the custom job do the download ?

Thanks,

**Comment by leiterenato** [comment]
`Would it be possible to skip that command and let the custom job do the download ?`
 - Not for all the tasks. Some datasets from Tensorflow Datasets (TFDS) requires a manual download of the dataset (XSUM is an example). To simplify our solution and make it more generic, we configure the dataset preparation (`tfds build`) in a separated step (in the README file).
 - Another reason why we recommend building the dataset before the training procedure, is because it can take many hours to finish and this would lead to waste of TPU time (waiting for this task to complete on CPU).
 - It is in our plans to create a KFP Pipeline which downloads the dataset before starting the training procedure.

If you don't run `tfds build`, it will try to download it for you (if the dataset is available in TFDS).
Sometimes it can fail and the training job will also fail (maybe it was your case).

I will close the issue for now, but feel free to post any issues you may find.
